services:
  bitcoin:
    build:
      context: .
      dockerfile: ./contrib/docker/bitcoin/Dockerfile
      args:
        BITCOIN_VERSION: "29.0"
    container_name: bitcoin
    restart: unless-stopped
    volumes:
      - ./data:/home/bitcoin/.bitcoin
    networks:
      - bitcoin-network
    ports:
      - "8332:8332"  # RPC
      - "8333:8333"  # P2P
      - "18332:18332"
      - "18333:18333"
      - "18443:18443" 
      - "18444:18444" 

  tor:
    build:
      context: .
      dockerfile: ./contrib/docker/tor/Dockerfile
    container_name: bitcoin-hidden-service
    environment:
      HS_bitcoin: "bitcoin:8332 bitcoin:8333 bitcoin:18332 bitcoin:18333 bitcoin:18443 bitcoin:18444"
    networks:
      - bitcoin-network
    volumes:
      - ./data/hidden-service:/var/lib/tor/bitcoin  # Persist onion addresses

networks:
  bitcoin-network:
    driver: bridge